-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 14:31:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema parking_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parking_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parking_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `parking_management` ;

-- -----------------------------------------------------
-- Table `parking_management`.`parking_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`parking_area` (
  `Area_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Area_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Area_Id`),
  UNIQUE INDEX `Area_Name_UNIQUE` (`Area_Name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking_management`.`parking_area_floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`parking_area_floors` (
  `Area_Id` INT(11) NOT NULL,
  `Floor_Number` INT(11) NOT NULL,
  `PermitType` VARCHAR(10) NOT NULL,
  `No_Spots` INT(3) NOT NULL,
  PRIMARY KEY (`Area_Id`, `Floor_Number`, `PermitType`),
  INDEX `floor_index` (`Floor_Number` ASC) VISIBLE,
  INDEX `permit_index` (`PermitType` ASC) VISIBLE,
  CONSTRAINT `parking_area_floor_FK`
    FOREIGN KEY (`Area_Id`)
    REFERENCES `parking_management`.`parking_area` (`Area_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking_management`.`parking_spots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`parking_spots` (
  `Area_Id` INT(11) NOT NULL,
  `Floor_Number` INT(11) NOT NULL,
  `Spot_Id` INT(11) NOT NULL,
  `IsBlocked` TINYINT(4) NULL DEFAULT '0',
  `PermitType` VARCHAR(10) NOT NULL,
  `Spot_UID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Area_Id`, `Floor_Number`, `Spot_Id`, `PermitType`),
  UNIQUE INDEX `Spot_UID_UNIQUE` (`Spot_UID` ASC) VISIBLE,
  INDEX `parking_slot_floor_FK_idx` (`Floor_Number` ASC) VISIBLE,
  INDEX `parking_slot_permit_FK_idx` (`PermitType` ASC) VISIBLE,
  CONSTRAINT `parking_permit_type_FK`
    FOREIGN KEY (`PermitType`)
    REFERENCES `parking_management`.`parking_area_floors` (`PermitType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `parking_slot_area_FK`
    FOREIGN KEY (`Area_Id`)
    REFERENCES `parking_management`.`parking_area` (`Area_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `parking_slot_floor_FK`
    FOREIGN KEY (`Floor_Number`)
    REFERENCES `parking_management`.`parking_area_floors` (`Floor_Number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2034
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking_management`.`system_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`system_users` (
  `User_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(10) NOT NULL,
  `HashedPassword` CHAR(128) NOT NULL,
  `Role` VARCHAR(20) NULL DEFAULT NULL,
  `IsRevoked` TINYINT(4) NOT NULL DEFAULT '0',
  `PermitType` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`User_Id`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 127
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking_management`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`reservations` (
  `Reservation_Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Spot_UID` INT(11) NOT NULL,
  `Start_Time` DATETIME NOT NULL,
  `End_Time` DATETIME NOT NULL,
  `NoShow` TINYINT(4) NULL DEFAULT '0',
  `OverStay` TINYINT(4) NULL DEFAULT '0',
  `User_Id` INT(11) NOT NULL,
  `Cart` TINYINT(4) NOT NULL DEFAULT '0',
  `Camera` TINYINT(4) NOT NULL DEFAULT '0',
  `History` TINYINT(4) NOT NULL DEFAULT '0',
  `Total` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`Spot_UID`, `End_Time`, `Start_Time`),
  UNIQUE INDEX `Reservation_Id_UNIQUE` (`Reservation_Id` ASC) VISIBLE,
  INDEX `Fk_Spot_UID_idx` (`Spot_UID` ASC) VISIBLE,
  INDEX `reservations_systems_users_FK` (`User_Id` ASC) VISIBLE,
  CONSTRAINT `Fk_Spot_UID`
    FOREIGN KEY (`Spot_UID`)
    REFERENCES `parking_management`.`parking_spots` (`Spot_UID`),
  CONSTRAINT `reservations_systems_users_FK`
    FOREIGN KEY (`User_Id`)
    REFERENCES `parking_management`.`system_users` (`User_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking_management`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking_management`.`user_details` (
  `User_Id` INT(11) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Sex` VARCHAR(45) NULL DEFAULT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `Address` VARCHAR(200) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(25) NULL DEFAULT NULL,
  `DL_Number` VARCHAR(25) NULL DEFAULT NULL,
  `DL_Expiry` DATE NOT NULL,
  `Reg_Number` VARCHAR(10) NOT NULL,
  `uta_Id` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`User_Id`),
  CONSTRAINT `User_Id_FK`
    FOREIGN KEY (`User_Id`)
    REFERENCES `parking_management`.`system_users` (`User_Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE `parking_management`.`system_users` 
ADD COLUMN `comment` VARCHAR(45) NULL AFTER `PermitType`;

ALTER TABLE `parking_management`.`reservations` 
DROP FOREIGN KEY `Fk_Spot_UID`;
ALTER TABLE `parking_management`.`reservations` 
ADD CONSTRAINT `Fk_Spot_UID`
  FOREIGN KEY (`Spot_UID`)
  REFERENCES `parking_management`.`parking_spots` (`Spot_UID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
